name: .NET Build

on:
  pull_request:
  push:
    branches: [ "main", "master" ]
    paths:
      - '*'
      - '!/readme.md'
      - '!/SECURITY.md'
      - '!/licence.txt'
      - '!/Benchmark/*'
      - '!/IntegrationTest/*'
      - '!/dists/*'
      - '!/assets/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore tests/RedisMemoryCacheInvalidation.Tests/RedisMemoryCacheInvalidation.Tests.csproj
    - name: Build
      run: dotnet build --no-restore tests/RedisMemoryCacheInvalidation.Tests/RedisMemoryCacheInvalidation.Tests.csproj -c Release /p:CI=true
    - name: Test
      run: dotnet test --no-build --verbosity normal tests/RedisMemoryCacheInvalidation.Tests/RedisMemoryCacheInvalidation.Tests.csproj -c Release --logger GitHubActions /p:CI=true
