name: Spell Checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  spellcheck:
    name: "Spellcheck"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5
        name: Check out the code
      - uses: actions/setup-node@v5
        name: Setup node
        with:
          node-version: "22"
      - run: |
          npm install -g cspell
        name: Install cSpell
      - run: cspell --config ./cSpell.json --no-progress
        name: Run cSpell
